#
#
# kps-api-support deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-support
  namespace: kps
  labels:
    app: kps-api-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-support
  template:
    metadata:
      labels:
        app: kps-api-support
    spec:
      containers:
      - name: kps-api-support
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-support:1.15
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 60m
            memory: 700Mi
          limits:
            cpu: 120m
            memory: 1800Mi                
        ports:
        - containerPort: 9080
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container
