#
#
# kps-api-support deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-support
  namespace: kps2
  labels:
    app: kps-api-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-support
  template:
    metadata:
      labels:
        app: kps-api-support
    spec:
      containers:
      - name: kps-api-support
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-support:1.12-dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 700Mi
          limits:
            cpu: 500m
            memory: 2000Mi                
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: ncp-container
