#
#
# kps-api-support service.yaml
#
# 
apiVersion: v1
kind: Service
metadata:
  name: kps-api-support
  namespace: kps
  labels:
    app: kps-api-support
spec:
  ports:
  - nodePort: 31907
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: kps-api-support
  type: NodePort

