#
#
# kps-api-common deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-common
  namespace: kps
  labels:
    app: kps-api-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-common
  template:
    metadata:
      labels:
        app: kps-api-common
    spec:
      containers:
      - name: kps-api-common
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-common:1.15
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 350m
            memory: 1200Mi
          limits:
            cpu: 800m
            memory: 3000Mi                
        ports:
        - containerPort: 9030
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1      
