#
#
# kps-api-common deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-common
  namespace: kps2
  labels:
    app: kps-api-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-common
  template:
    metadata:
      labels:
        app: kps-api-common
    spec:
      containers:
      - name: kps-api-common
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-common:1.10-dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 105m
            memory: 1800Mi                
        ports:
        - containerPort: 9030
      imagePullSecrets:
        - name: ncp-container
