#
#
# kps-zuul-gateway deployment.yaml
#
# 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-zuul-gateway
  namespace: kps2
  labels:
    app: kps-zuul-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kps-zuul-gateway
  template:
    metadata:
      labels:
        app: kps-zuul-gateway
    spec:
      containers:
      - name: kps-zuul-gateway
        image: kps-container-registry.ncr.gov-ntruss.com/kps-zuul-gateway:1.3
        imagePullPolicy: Always
      imagePullSecrets:
        - name: ncp-container
