#
#
# kps-zuul-gateway deployment.yaml
#
# 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-zuul-gateway
  namespace: kps
  labels:
    app: kps-zuul-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-zuul-gateway
  template:
    metadata:
      labels:
        app: kps-zuul-gateway
    spec:
      containers:
      - name: kps-zuul-gateway
        image: kps-container-registry.ncr.gov-ntruss.com/kps-zuul-gateway:1.9
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container
