#
#
# kps-zuul-gateway deployment.yaml
#
# 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-zuul-gateway
  namespace: kps
  labels:
    app: kps-zuul-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kps-zuul-gateway
  template:
    metadata:
      labels:
        app: kps-zuul-gateway
    spec:
      containers:
      - name: kps-zuul-gateway
        image: kps-container-registry.ncr.gov-ntruss.com/kps-zuul-gateway:1.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 700Mi
          limits:
            cpu: 50m
            memory: 1800Mi                
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1         
