#
#
# kps-api-edu deployment.yaml
#
# 
apiVersion: v1
kind: Service
metadata:
  name: kps-zuul-gateway
  namespace: kps
  labels:
    app: kps-zuul-gateway
spec:
  ports:
    - port: 9021
      protocol: TCP
      targetPort: 9021
  selector:
    app: kps-zuul-gateway
  type: ClusterIP

