#
#
# kps-api-operate deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-operate
  namespace: kps
  labels:
    app: kps-api-operate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-operate
  template:
    metadata:
      labels:
        app: kps-api-operate
    spec:
      containers:
      - name: kps-api-operate
        image: loopy456/kps-api-operate:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9070
