#
#
# kps-api-operate deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-operate
  namespace: kps2
  labels:
    app: kps-api-operate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-operate
  template:
    metadata:
      labels:
        app: kps-api-operate
    spec:
      containers:
      - name: kps-api-operate
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-operate:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 9070
      imagePullSecrets:
        - name: ncp-container