#
#
# kps-api-operate deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-operate
  namespace: kps
  labels:
    app: kps-api-operate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-operate
  template:
    metadata:
      labels:
        app: kps-api-operate
    spec:
      containers:
      - name: kps-api-operate
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-operate:1.13
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 1000Mi
          limits:
            cpu: 800m
            memory: 2500Mi                
        ports:
        - containerPort: 9070
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      