#
#
# kps-api-operate service.yaml
#
# 
apiVersion: v1
kind: Service
metadata:
  name: kps-api-operate
  namespace: kps
  labels:
    app: kps-api-operate
spec:
  ports:
  - nodePort: 31906
    port: 9070
    protocol: TCP
    targetPort: 9070
  selector:
    app: kps-api-operate
  type: NodePort

