#
#
# kps-api-business deployment.yaml
#
# s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-business
  namespace: kps2
  labels:
    app: kps-api-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-business
  template:
    metadata:
      labels:
        app: kps-api-business
    spec:
      containers:
      - name: kps-api-business
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-business:1.16-dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 40m
            memory: 700Mi
          limits:
            cpu: 200m
            memory: 1400Mi                
        ports:
        - containerPort: 9040
      imagePullSecrets:
        - name: ncp-container