#
#
# kps-api-business deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-business
  namespace: kps
  labels:
    app: kps-api-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-business
  template:
    metadata:
      labels:
        app: kps-api-business
    spec:
      containers:
      - name: kps-api-business
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-business:1.13
        imagePullPolicy: Always
        ports:
        - containerPort: 9040
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container