#
#
# kps-web-user-en service.yaml
#
# si
apiVersion: v1
kind: Service
metadata:
  name: kps-web-user-en
  namespace: kps2
  labels:
    app: kps-web-user-en
spec:
  ports:
    - port: 8070
      protocol: TCP
      targetPort: 8070
  selector:
    app: kps-web-user-en
  type: ClusterIP
