#
#
# kps-api-content deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-content
  namespace: kps2
  labels:
    app: kps-api-content
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kps-api-content
  template:
    metadata:
      labels:
        app: kps-api-content
    spec:
      containers:
      - name: kps-api-content
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-content:1.29-dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 700Mi
          limits:
            cpu: 500m
            memory: 2000Mi                
        ports:
        - containerPort: 9060
      imagePullSecrets:
        - name: ncp-container

