#
#
# kps-api-edu deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-edu
  namespace: kps
  labels:
    app: kps-api-edu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-edu
  template:
    metadata:
      labels:
        app: kps-api-edu
    spec:
      containers:
      - name: kps-api-edu
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-edu:1.46
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 800Mi
          limits:
            cpu: 700m
            memory: 2000Mi                
        ports:
        - containerPort: 9050
        volumeMounts:
        - mountPath: /var/vcap/data
          name: backup-storage
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pv-claim
      imagePullSecrets:
        - name: ncp-container
  