#
#
# kps-api-edu deployment.yaml
#
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-api-edu
  namespace: kps2
  labels:
    app: kps-api-edu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kps-api-edu
  template:
    metadata:
      labels:
        app: kps-api-edu
    spec:
      containers:
      - name: kps-api-edu
        image: kps-container-registry.ncr.gov-ntruss.com/kps-api-edu:1.6-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 9050
      imagePullSecrets:
        - name: ncp-container
  