#
#
# kps-api-edu service.yaml
#
# 
#
apiVersion: v1
kind: Service
metadata:
  name: kps-api-edu
  namespace: kps2
  labels:
    app: kps-api-edu
spec:
  ports:
    -  port: 9050
       protocol: TCP
       targetPort: 9050
  selector:
    app: kps-api-edu
  type: clusterIP

